name: deploy website preview
on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: vercel-action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.ZEIT_TOKEN }}
          github-comment: false
          vercel-org-id: ${{ secrets.NOW_ORG_ID }}
          vercel-project-id: ${{ secrets.NOW_PROJECT_ID_STATIC }}
      - name: preview-url
        run: |
          echo ${{ steps.vercel-action.outputs.preview-url }}
